### ISSUE TITLE
new tag swep   broke

### ISSUE THREAD

**Issue by xxsoundboardxx** [swampservers/contrib#144]
Somehow they are trying to tag someone and they got this error code.  
Issue found they sent from discord 

![](https://i.imgur.com/OuV0jW5.png)

**Comment by swampservers** [comment]
the actual error is in the console, thanks for reporting it tho

**Comment by Ugleh** [comment]
This is now resolved.

**Comment by xxsoundboardxx** [comment]
Ah, well that's good news should i closed this session?
