### ISSUE TITLE
Create a tutorial system

### ISSUE THREAD

**Issue by swampservers** [swampservers/contrib#185]
Add popups like "hold q to request a video" and a checkbox in the tab menu to disable it

**Comment by GrateBrittan** [comment]
bet

**Comment by swampservers** [comment]
@PYROTEKNIK doesn't need to be complicated, just needs to be completed

**Comment by PYROTEKNIK** [comment]
was this completed to satisfaction?

**Comment by swampservers** [comment]
@PYROTEKNIK weren't the hooks supposed to be contextual (eg tell people to hold Q when they walk into the theater)

**Comment by PYROTEKNIK** [comment]
I remember you asking me to keep it simple. I believe all hints are displayed at random but some are triggered  by hooks

**Comment by swampservers** [comment]
https://github.com/swampservers/contrib/blob/master/lua/autorun/gamehints.lua ??? I dont see any hooks

**Comment by swampservers** [comment]
I made my own version of it that pops the hints up more obviously and deterministically
