### ISSUE TITLE
How to setup a test environment?

### ISSUE THREAD

**Issue by dextonanderson** [swampservers/contrib#194]
This may be a simple answer, but it wasn't in the README and I am new to Gmod add-on development. How do I properly test this add-on?

I tried cloning the repo into STEAMDIR/steamapps/common/GarrysMod/garrysmod/addons and that does initialize the add-on (I loaded a Single Player sandbox instance). However, there are lua errors regarding Minecraft and other autorun lua items. The point shop menu opens but does not display items.

Is there a dependency I need? Something I missed? I'd like to contribute some things once I can get it working.

**Comment by dextonanderson** [comment]
Additionally, I have no other addons installed and no workshop subscriptions. I have the cinema_swamp_v3 map installed locally.

**Comment by swampservers** [comment]
The problem is you've missing the serverside part of the code which I can't share.

If you just want to make a SWEP or something you don't need to test it in this addon. If you want to work on something in the addon, depending on what it is you can probably isolate it and work on it. Let me know if you need more help

**Comment by dextonanderson** [comment]
Oh okay. So the primary way of additional contributions is to isolate the feature being added and patch it into this repo once completed?

**Comment by swampservers** [comment]
It really just depends on what you're trying to do

**Comment by dextonanderson** [comment]
There was one thing I particular I wanted to add. It may be the case that it can't be done in the add-on and rather the map. But, I wanted to add Otis elevator voice announcements to the trump tower elevator.

https://www.soundboard.com/sb/OtisElevatorVoiceAnnouncements

Eg, going up -> "Going up",
going down -> " Going down",
Ground floor - 4th floor have their specific callout as well.
