### ISSUE TITLE
Text Muting Oversight

### ISSUE THREAD

**Issue by ghost** [swampservers/contrib#53]
While being able to hide the text chat of players is a good idea, I don't think it has been implemented well. I normally often mute micspammers, but now I won't be able to see what they're saying. It's either listen to their annoying micspam, or miss out on their chat.

This feature should really be implemented into another button, so that muting doesn't affect both voice and text at the same time.

**Comment by Milwacko** [comment]
^

**Comment by chev2** [comment]
If you aren't aware already, this is now done and is now live on the server. >>#65 
This can be closed
